###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux x86_64(Host ID vlsj-brianw)
#  Generated on:      Fri Apr 19 14:42:55 2013
#  Design:            
#  Command:           save_global DATA/leon.globals
###############################################################
#
# Version 1.1
#

set BLOCK_NAME async_fifo

set conf_qxconf_file {NULL}
set conf_qxlib_file {NULL}
set defHierChar {/}
set init_design_settop 0
set init_gnd_net {VSS}
set init_lef_file {/cadence_pdk/xfab/XKIT/x_all/cadence/XFAB_Digital_Power_RefKit-cadence/v1_3_1/pdk/xh018/cadence/v8_0/techLEF/v8_0_1_1/xh018_xx51_HD_MET5_METMID.lef \
    /cadence_pdk/xfab/XKIT/x_all/cadence/XFAB_Digital_Power_RefKit-cadence/v1_3_1/pdk/xh018/diglibs/D_CELLS_JIHD/v4_1/LEF/v4_1_1/xh018_D_CELLS_JIHD.lef \
}
set init_mmmc_file {../scripts/mmmc.tcl}
set init_pwr_net {VDD}
set init_verilog {../in/${BLOCK_NAME}.vg}
set init_verilog {../in/async_fifo.vg}
set lsgOCPGainMult 1.000000
