###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux x86_64(Host ID vlsj-brianw)
#  Generated on:      Fri Apr 19 14:42:55 2013
#  Design:            
#  Command:           save_global DATA/leon.globals
###############################################################
#
# Version 1.1
#

set conf_qxconf_file {NULL}
set conf_qxlib_file {NULL}
set defHierChar {/}
set init_design_settop 0
set init_gnd_net {VSS}
set init_lef_file {../../../lef/gsclib045.fixed2.lef}
set init_mmmc_file {../in/mmmc.tcl}
set init_pwr_net {VDD}
set lsgOCPGainMult 1.000000
